###################################################################
# include file for an individual machine by A.Sekimoto   
########################################################### machine
SYSTEM = gfortran, please take care for endian #
########################################################## compiler
F77 = h5pfc 
F90 = h5pfc 
CC = gcc
#
CMPI_LIB =
OMP_FLAGS =
#
########################################################### library
LAPACKDIR = /opt/homebrew/opt/lapack/
HDF5LIB = /opt/homebrew/Cellar/hdf5-mpi/1.12.2_1/lib/
FFTWINC = /opt/homebrew/Cellar/fftw/3.3.10_1/include/
#
#BLAS = blas # interface library (GNU fortran)
#LAPACK = lapack
EXTLIBS = -L$(LAPACKDIR) -lblas -llapack
EXTHDF5 = -L$(HDF5LIB) 
EXTFFTW = -I$(FFTWINC) -lfftw3 
#################################################### compiler flags
# choose one of belows:
# for debugging
#F90OPT = -c -fbounds-check  $(EXTFFTW) # for gfortran without CUDA
#LFOPT  =  -fbounds-check -fconvert='little-endian'  $(EXTLIBS) $(EXTFFTW) $(EXTHDF5)   
# for productive runs
F90OPT = -c -O2 -fconvert='little-endian' $(EXTFFTW) 
LFOPT  = -O2 -fconvert='little-endian'  $(EXTLIBS) $(EXTFFTW) $(EXTHDF5)  
#
#F90OPT = -c -march='corei7-avx' -fconvert='little-endian' $(EXTFFTW)
#LFOPT  = -march='corei7-avx'  -fconvert='little-endian'  $(EXTLIBS) $(EXTFFTW) $(EXTHDF5) 
#
########################################################
F77OPT=$(F90OPT)
F77FLAGS=$(F90OPT) 
LFLAGS = $(LFOPT)
##############################################################  END
